baseURL = "https://curlpgh.org/"
languageCode = "en-us"
title = "Pittsburgh Curling Club"
theme = "bs"
relativeURLS = true

[params]
  twitter = "https://twitter.com/PghCurlingClub"
  facebook = "https://www.facebook.com/pittsburghcurlingclub"
  instagram = "https://www.instagram.com/pghcurling"

[[menu.main]]
  name = "Learn to Curl"
  url = "/learn-to-curl"
  weight = 1

[[menu.main]]
  name = "Members"
  weight = 2

[[menu.main]]
  name = "Current Draw Info"
  parent = "Members"
  url = "/members/current-draw-info"
  weight = 1

[[menu.main]]
  name = "Scheduling"
  parent = "Members"
  url = "/members/scheduling"
  weight = 2

[[menu.main]]
  name = "Calendar"
  parent = "Members"
  url = "/members/calendar"
  weight = 3

[[menu.main]]
  name = "Registration"
  parent = "Members"
  url = "/members/registration"
  weight = 4

[[menu.main]]
  name = "Group Events"
  url = "/group-events"
  weight = 3

[[menu.main]]
  name = "Fund Raising"
  weight = 4

[[menu.main]]
  name = "Donations"
  parent = "Fund Raising"
  url = "/fund-raising/donations"
  weight = 1

[[menu.main]]
  name = "Giant Eagle Giftcards"
  parent = "Fund Raising"
  url = "/fund-raising/giant-eagle-giftcards"
  weight = 2

[[menu.main]]
  name = "Amazon Smile"
  parent = "Fund Raising"
  url = "/fund-raising/amazon-smile"
  weight = 3

[[menu.main]]
  name = "About"
  weight = 5

[[menu.main]]
  name = "Board"
  parent = "About"
  url = "/about/board"
  weight = 1

[[menu.main]]
  name = "Board Meetings"
  parent = "About"
  url = "/about/board-meetings"
  weight = 2

[[menu.main]]
  name = "Bylaws / Policies"
  parent = "About"
  url = "/about/bylaws-policies"
  weight = 3

[[menu.main]]
  name = "Minutes"
  parent = "About"
  url = "/minutes"
  weight = 4

[[menu.main]]
  name = "Waiver"
  parent = "About"
  url = "/about/waiver"
  weight = 5

[[menu.main]]
  name = "Contact"
  parent = "About"
  url = "/about/contact"
  weight = 6

[[menu.main]]
  name = "COVID"
  weight = 6

[[menu.main]]
  name = "COVID Response Plan"
  parent = "COVID"
  url = "/covid/covid-response-plan"
  weight = 1

[[menu.main]]
  name = "Phased Reopening Plan"
  parent = "COVID"
  url = "/covid/phased-reopening-plan"
  weight = 2
